services:
  go-app:
    image: golang:latest
    container_name: go_app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    command: ["go", "run", "main.go"]
    tty: true
